### ISSUE TITLE
New version (OpenWrt 19.07.6)

### ISSUE THREAD

**Issue by itProfi** [max255/node-red-contrib-xiaomi-gateway#1]
Are you plan add support new openwrt 19.07.6 with new LED driver - https://github.com/openlumi/openwrt/commit/1a3adc95ccee91cad8766e413cc038cd5fb1b778  ?
This tool - like as example - https://github.com/Beetle-II/lumi/commit/8d4d2b20961dfe887f48ba4a4b83ca70a90ba74c

**Comment by max255** [comment]
> new openwrt 19.07.6
Yes, I plan a little later. But you can still configure the gateway-led node yourself. 
![path](https://user-images.githubusercontent.com/10141227/107127734-301f3980-68c9-11eb-9c3a-d840c019d59e.JPG)

**Comment by itProfi** [comment]
ok, thanks!
